
INSERT INTO gestor_calidad.macroproceso (id_macro, nombre_macro) VALUES 
('GG', 'Gestión Gerencial'),
("GQ", "Gestión de Calidad"),
("GL_2", "Gestión Logística"),
("EF", "Dispensación"),
("GV", "Gestión Comercial Y Mercadeo"),
("GF", "Gestión Financiera y Administrativa"),
("CM", "Gestion de Cuentas Medicas"),
("TH_2", "Gestión del Talento Humano"),
("TI", "Gestión de Tecnología e Información"),
("IN", "Inteligencia de Negocios"),
("CI" , "Control Interno");

INSERT INTO procesos (id_proceso, nombre_proceso, id_macro_fk) VALUES 
('AG', 'Asistente de Gerencia', 'GG'),
('RF', 'Revisoría Fiscal', 'GG'),
('AJ', 'Asesoría Jurídica', 'GG'),
('SI', 'SIAU', 'GG'),
('CO', 'Comunicaciones', 'GG'),
('GD', 'Gestión Documental', 'GQ'),
('SR', 'Sistema de Administración del Riesgo - SAR', 'GQ'),
('GO', 'Gestión Operativa', 'GL_2'),
('GI', 'Gestión de Inventarios', 'GL_2'),
('EF', 'Dispensación', 'EF'),
('GV', 'Ventas', 'GV'),
('GL', 'Licitaciones', 'GV'),
('CT', 'Contabilidad', 'GF'),
('TE', 'Tesorería', 'GF'),
('PC', 'Cartera', 'GF'),
('RA', 'Recursos Administrativos', 'GF'),
('ACM', 'Auditoría de cuenta médicas', 'CM'),
('FR', 'Facturación y radicación', 'CM'),
('TH', 'Talento Humano', 'TH_2'),
('BI', 'Bienestar', 'TH_2'),
('SVG', 'Servicios Generales', 'TH_2'),
('SST', 'SGSST', 'TH_2'),
('DS', 'Desarrollo', 'TI'),
('SP', 'Soporte', 'TI'),
('GC', 'Planeación de la Compra', 'IN'),
('GIN', 'Gestión de la información', 'IN'),
('GP', 'Parametrización', 'IN'),
('CI2', 'Control Interno', 'CI');